### ISSUE TITLE
Repository "Other"

### ISSUE THREAD

**Issue by LukasBuecherl** [fluentverification/CaseStudies_StochasticModelChecking#15]
Look at the models in the repository "other" and decided where they need to go

**Comment by LukasBuecherl** [comment]
@landonjefftaylor @bryantisraelsen could you check out the .ivy models? We probably won't include them in the paper so they should be moved somewhere else.

**Comment by bryantisraelsen** [comment]
I moved the IVy models to the ragtimer repo. See my pull request.
