### ISSUE TITLE
Update questions for user-input biochemical reaction network

### ISSUE THREAD

**Issue by zgzn** [fluentverification/CaseStudies_StochasticModelChecking#2]
When running python3 on reactions_v2.py, the script interacts with the user with the questions below:

> Which chemical is going to be monitored? Gbg
> What is the target number for this chemical? 50
> Are you interested in seeing when the chemical is above or below the specified number? (type either above or below): above

First, rename "chemical" to "species" in these questions, and all other questions if applicable. Secondly, the statement of the last question listed above can be improved. Do we allow the user to check greater-than-or-equal, less-than-or-equal, and equality relations? The above question's statement seems to allow only strictly greater-than and less than relations. Maybe we can instead provide an itemized list of (in-)equalities for the user to choose? For example, after the user specifies Gbg and 50, the script can list these items below for the user to choose:

> 1) Gbg = 50
> 2) Gbg > 50
> 3) Gbg >= 50
> 4) Gbg < 50
> 5) Gbg <= 50

**Comment by bryantisraelsen** [comment]
I will work fixing the issues and let you know when I have. Thanks!

**Comment by bryantisraelsen** [comment]
I made the adjustments that you specified, the only difference is that I do not provide the equality option '=' for a guard that can be chosen. So instead it displays the following

   Which species is going to be monitored? gbg
   What is the target number for this species? 50
   Which option is your desired guard?

    1: gbg >= 50
    2: gbg > 50
    3: gbg <= 50
    4: gbg < 50

**Comment by zgzn** [comment]
Thank you, Bryant. Do you think we can add the equality option as the goal? Will adding this option affect the reaction priority determination?

**Comment by bryantisraelsen** [comment]
If we did add the equality option, in order to keep our priority determination the script would have to interpret it as either a '>=' or a '<=' depending on what the target species is initialized to. Is that what you had in mind?

**Comment by zgzn** [comment]
The interpretation as either '>=' or '<=' will have to depend on the 
initial and target value difference. We can discuss it at our meeting 
tomorrow before you make changes in your script.


bryantisraelsen wrote on 7/7/22 12:15 PM:
